# Welcome to Jekyll!
#

# Site settings
title: bathompso.com
description: |
  "The Corps Issued Me A Rifle, Not Wings"
owner: Ben Thompson # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: bathompso@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bathompso.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/bathompso
  github: https://github.com/bathompso
  linkedin-square: https://linkedin.com/in/bathompso
  facebook-official: https://facebook.com/bathompso
  #google-plus-square: https://plus.google.com/u/0/+<username>
  email: mailto:bathompso@gmail.com
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: redcarpet
highlighter: rouge
permalink: /:categories/:slug/
exclude: ['styles/config.rb', 'styles/sass/']
relative_permalinks: false

tag_title_prefix: ''
tag_title_suffix: ' Blog Posts'
tag_dir: 'blog/tag'

image:
    source: images
    output: generated
    markup: picture
    presets:
        default:
            ppi: [1, 1.5]
        blog_landing:
            width: 555
            height: 350
        blog_thumbnail:
            width: 150
            height: 150
        blog_main:
            width: 1400
            height: 600
