name: bathompso.com
title: bathompso.com
markdown: redcarpet
highlighter: pygments
permalink: /:categories/:title/

url: http://www.bathompso.com
fburl: http://bathompso.com

exclude: ['styles/config.rb', 'styles/sass/']
relative_permalinks: false

tag_title_prefix: ''
tag_title_suffix: ' Blog Posts'
tag_dir: 'blog/tag'

comments:
    facebook:
      appid: 148947288529876
      num_posts: 10
      width: 600
      colorscheme: light

image:
    source: media/fullsize
    output: generated
    presets:
        royalslider:
            attr:
                class: rsImg
            height: 500
            width: 940
        blogsumm:
            height: 300
            width: 613
        researchbanner:
            attr:
                class: researchmainimg
            height: 250
            width: 1000
        fullblog:
            attr:
                class: blogtextimg
            width: 940
        lessonsumm:
            attr:
                class: lessonsummimg
            height: 200
            width: 200
        lessontext:
            attr:
                class: lessontextimg
            width: 300
